32
l3r8yJ/volpi-qa pull request #144
Opened 2023-06-19 20:29 UTC by Andrew-Sem

Closes #32

2023-06-19 21:54 UTC, l3r8yJ requested changes
@Andrew-Sem take a look at my comments below, please 

move this env var [here](https://github.com/l3r8yJ/volpi-qa/blob/master/docker.env)

2023-06-19 21:54 UTC, l3r8yJ commented on qa-admin/src/main/client/Dockerfile
> +ARG VITE_ADMIN_API_URL
remove from here

2023-06-19 21:54 UTC, l3r8yJ commented on qa-admin/src/main/client/Dockerfile
> +ENV VITE_ADMIN_API_URL=$VITE_ADMIN_API_URL
and here

2023-06-20 14:17 UTC, Andrew-Sem commented
@l3r8yJ take a look at this, please

2023-06-20 15:01 UTC, l3r8yJ approved these changes
@Andrew-Sem ltgm

2023-06-20 15:02 UTC, merged